CREATE SCHEMA IF NOT EXISTS sales CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'sales'@'%' IDENTIFIED BY 'Laba#Diena';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP,
    INDEX, ALTER, CREATE TEMPORARY TABLES, REFERENCES,
    CREATE VIEW, SHOW VIEW
    ON sales.* TO 'sales'@'%' IDENTIFIED BY 'Laba#Diena';

USE sales;
SET default_storage_engine = InnoDB;